﻿<Project Sdk="Microsoft.NET.Sdk">

	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI.Foundry.Hosting"
			Version="1.15.0-preview.260722.1" />
		<PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
	</ItemGroup>

</Project>